# This is a workflow to being called from appdev-devops repo in genesiscicd
#  NPM web build workflow v0.0.1

name: Web Deploy

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      branch:
        required: false
        type: string
    secrets:
      JFROG_USERNAME:
        required: true
      JFROG_EMAIL:
        required: true
      JFROG_PASSWORD:
        required: true
      NPM_SETTING:
        required: true
      JFROG_NPM_AUTH_TOKEN:
        required: true
    
env:
  REPO_NAME: ${{ inputs.repo_name }}
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    env:
      JFROG_USERNAME: ${{secrets.JFROG_USERNAME}}
      JFROG_EMAIL: ${{secrets.JFROG_EMAIL}}
      JFROG_PASSWORD: ${{secrets.JFROG_PASSWORD}}
      NPM_SETTING: ${{ secrets.NPM_SETTING }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Env Setup
        run:  |
              echo "PRODUCT_BASE=$(pwd)" >> $GITHUB_ENV
              echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV
              echo "PRODUCT_NAME=$(git config --get remote.origin.url | cut -d"." -f2 | cut -d"/" -f3 | cut -d"-" -f1 | cut -d"_" -f2)" >> $GITHUB_ENV #NOTE: only works with SSH repo urls + will cause issues with bny_investments
              echo "OUTPUT=$(git config --get remote.origin.url | cut -d"." -f2 | cut -d"/" -f3 | cut -d"-" -f1 | cut -d"_" -f2)-web-$(git describe --tags).zip" >> $GITHUB_ENV

      - name: Env Setup for nightly build
        if: ${{ inputs.branch == 'develop' ||  inputs.branch == 'main' ||  inputs.branch == 'master' || inputs.branch == '0.0.0' }}
        run:  |
              echo "VERSION=${{ inputs.branch }}" >> $GITHUB_ENV
              echo "OUTPUT=$(git config --get remote.origin.url | cut -d"." -f2 | cut -d"/" -f3 | cut -d"-" -f1 | cut -d"_" -f2)-web-${{ inputs.branch }}.zip" >> $GITHUB_ENV
      
      - name: Sonar Setup
        run:  |
              echo "Sonar Setup:"
              date
              combined=""
              echo "sonar.projectKey="${{ env.REPO_NAME }} > sonar-project.properties
              cd "${{ env.PRODUCT_BASE }}"/packages/apps/
              ls -lart
              for i in ./*
               do
                 if [ -d "$i" ]
                   then
                     token=${{ env.PRODUCT_BASE }}/packages/apps/$i/dist
                     combined="${combined}${combined:+,}$token"
                     echo $combined
                 fi
               done
              echo "sonar.sources="$combined >> sonar-project.properties     
              cat sonar-project.properties
              cd ${{ env.PRODUCT_BASE }}
              
      - name: Artifactory Setup
        run: |
              echo "Artifactory:"
              date
              #chmod 664 /usr/local/etc/npmrc
              npm config set @genesisglobal:registry https://genesisglobal.jfrog.io/artifactory/api/npm/npm-local/
              npm config set //genesisglobal.jfrog.io/artifactory/api/npm/npm-local/:always-auth true
              cat ~/.npmrc
              
      - name: Configure Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://genesisglobal.jfrog.io/artifactory/api/npm/github-packages/
          scope: '@genesislcap'
          
      - name: Install and NPM Config
        run:  |
              npm config set @genesisglobal:registry https://genesisglobal.jfrog.io/artifactory/api/npm/npm-local/
              npm config set //genesisglobal.jfrog.io/artifactory/api/npm/npm-local/:username ${{secrets.JFROG_USERNAME}}
              npm config set //genesisglobal.jfrog.io/artifactory/api/npm/npm-local/:_auth ${{secrets.JFROG_NPM_AUTH_TOKEN}}
              npm config set //genesisglobal.jfrog.io/artifactory/api/npm/npm-local/:email ${{secrets.JFROG_EMAIL}}
              npm config set //genesisglobal.jfrog.io/artifactory/api/npm/npm-local/:always-auth true
              echo "**************************************************************************************************************"
              echo "Install:"
              echo "**************************************************************************************************************"
              npm run bootstrap
              npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GPR_READ_TOKEN}} 
          
      - name: Build
        run: npm run build      
             
      - name: Package and Publish
        run:  |
              echo "Package:"
              date
              sudo apt-get install zip unzip
              echo $(pwd)
              mkdir -p ${{ env.PRODUCT_BASE }}/web
              cd ${{ env.PRODUCT_BASE }}/packages/apps/
              for i in ./*
               do
                 if [ -d "${{ env.PRODUCT_BASE }}/packages/apps/$i/dist" ]
                   then
                     mkdir -f ${{ env.PRODUCT_BASE }}/web/$i
                     cp -rf ${{ env.PRODUCT_BASE }}/packages/apps/$i/dist/* ${{ env.PRODUCT_BASE }}/web/$i
                     ls -lart ${{ env.PRODUCT_BASE }}/web/$i
                 fi
               done
               
              cd ${{ env.PRODUCT_BASE }}/web/
              zip -r ${{ env.PRODUCT_BASE }}/${{ env.output }} *				
              echo ${{ env.OUTPUT }}
              ls | grep zip
              curl -u ${{ secrets.JFROG_USERNAME }}:"${{secrets.JFROG_PASSWORD}}" -X PUT "https://genesisglobal.jfrog.io/artifactory/product/${{ env.PRODUCT_NAME }}/web/${{ env.OUTPUT }}" -T ${{ env.OUTPUT }} -v
